name: Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.repository == 'LuisEnMarroquin/json-as-xlsx'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
      - name: Build JavaScript file
        run: npm run build
      - name: Set environment variables
        run: |
          git fetch --all --tags
          echo "TAG_VERSION=$(git describe --abbrev=0)" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$(node -e "console.log('v' + require('./package.json').version)")" >> $GITHUB_ENV
          echo Env TAG_VERSION ${{ env.TAG_VERSION }} and CURRENT_VERSION ${{ env.CURRENT_VERSION }}
      - name: Publish package to NPM
        if: ${{ env.TAG_VERSION != env.CURRENT_VERSION }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
          npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.TOKEN_NPM }}
      - name: Create GitHub release
        if: ${{ env.TAG_VERSION != env.CURRENT_VERSION }}
        run: |
          echo ${{ secrets.TOKEN_GITHUB }} > nothing.md
          gh auth login --with-token < nothing.md
          gh release create ${{ env.CURRENT_VERSION }} -F README.md -t "Released ${{ env.CURRENT_VERSION }}"
      - name: Build VueJS project
        run: |
          npm run build-client
          cp CNAME dist/CNAME
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          folder: dist
          branch: gh-pages
          git-config-name: LuisEnMarroquin
          git-config-email: mluis651@gmail.com
